# Generated by Django 2.1.3 on 2019-10-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='userimg_fl',
            field=models.FileField(default='', upload_to='./usersimg/', verbose_name='头像图片储存路径'),
        ),
    ]
