# Generated by Django 2.1.3 on 2019-10-09 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_userinfo_userimg_fl'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户信息'},
        ),
    ]
